version: '2'
services:
  
  bot:
    image: redelivre/alpine-node:${NODE_VERSION}-telegraf
    build:
      context: .
      dockerfile: Dockerfile.${NODE_VERSION}
      args:
        - "username=$username"
        - "botname=$TELEGRAM_NAME"
        - "token=$TELEGRAM_TOKEN"
        - "domain=$TELEGRAM_DOMAIN"
